# Generated by Django 2.0.3 on 2018-05-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_auto_20180508_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='branch',
            field=models.CharField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'fouth'), (5, 'fifth'), (6, 'sixth'), (7, 'seventh'), (8, 'eighth')], default='CSE', max_length=5),
        ),
        migrations.AlterField(
            model_name='paper',
            name='semester',
            field=models.IntegerField(choices=[('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('EEE', 'Electronics & Electrical Engineering'), ('BBA', 'Bachelor of Business Administration'), ('BCA', 'Bachelors in Computer Application'), ('Animation', 'Animation Department')], default=1),
        ),
    ]
