# Generated by Django 2.0.3 on 2018-05-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_auto_20180508_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='slug',
        ),
        migrations.AlterField(
            model_name='paper',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('EEE', 'Electronics & Electrical Engineering'), ('BBA', 'Bachelor of Business Administration'), ('BCA', 'Bachelors in Computer Application'), ('Animation', 'Animation & Multimedia')], default='CSE', max_length=5),
        ),
        migrations.AlterField(
            model_name='paper',
            name='semester',
            field=models.IntegerField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'fouth'), (5, 'fifth'), (6, 'sixth'), (7, 'seventh'), (8, 'eighth')], default=1),
        ),
        migrations.AlterField(
            model_name='paper',
            name='time_period',
            field=models.CharField(choices=[('midsem', 'midsem'), ('endsem', 'endsem')], default='midsem', max_length=6),
        ),
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.IntegerField(choices=[(2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018')], default='', max_length=4),
        ),
    ]
