# Generated by Django 2.0.3 on 2018-05-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_auto_20180508_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.IntegerField(choices=[(2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018')], default=''),
        ),
    ]
