# Generated by Django 2.0.3 on 2018-05-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('branch', models.CharField(max_length=250)),
                ('semester', models.IntegerField()),
                ('subject', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('year', models.CharField(max_length=10)),
                ('time_period', models.CharField(max_length=10)),
                ('uploaded_by', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='files')),
            ],
        ),
    ]
