# Generated by Django 2.0.3 on 2018-05-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20180508_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='semester',
            field=models.IntegerField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'fourth'), (5, 'fifth'), (6, 'sixth'), (7, 'seventh'), (8, 'eighth')], default=1),
        ),
    ]
